/**
 * @license
 * Copyright (c) Noldova.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */

export type { IAppUpdater } from "../interfaces/i-app-updater.js";
export type { IApplicationHost } from "../interfaces/i-application-host.js";
export type { IClipboardHost } from "../interfaces/i-clipboard-host.js";
export type { ICloseGuard } from "../interfaces/i-close-guard.js";
export type { IDesktopLog } from "../interfaces/i-desktop-log.js";
export type { IDesktopProcess } from "../interfaces/i-desktop-process.js";
export type { IDesktopWindow } from "../interfaces/i-desktop-window.js";
export type { IDeviceFileStore } from "../interfaces/i-device-file-store.js";
export type { IDialogHost } from "../interfaces/i-dialog-host.js";
export type { IDisplayHost } from "../interfaces/i-display-host.js";
export type { IDockHost } from "../interfaces/i-dock-host.js";
export type { IElectron } from "../interfaces/i-electron.js";
export type { IFeedResponse } from "../interfaces/i-feed-response.js";
export type { IIpcEvent } from "../interfaces/i-ipc-event.js";
export type { IIpcHost } from "../interfaces/i-ipc-host.js";
export type { IMenuHost } from "../interfaces/i-menu-host.js";
export type { INotificationHost } from "../interfaces/i-notification-host.js";
export type { ITray } from "../interfaces/i-tray.js";
export type { ITrayHost } from "../interfaces/i-tray-host.js";
export type { IParentPort } from "../interfaces/i-parent-port.js";
export type { IPathCommandFiles } from "../interfaces/i-path-command-files.js";
export type { IPermissionHost } from "../interfaces/i-permission-host.js";
export type { IPreventableEvent } from "../interfaces/i-preventable-event.js";
export type { IProgramHost } from "../interfaces/i-program-host.js";
export type { IQuitHost } from "../interfaces/i-quit-host.js";
export type { IQuitPrompt } from "../interfaces/i-quit-prompt.js";
export type { IRuntimeConnection } from "../interfaces/i-runtime-connection.js";
export type { IRuntimeLauncher } from "../interfaces/i-runtime-launcher.js";
export type { IUpdateCheckLock } from "../interfaces/i-update-check-lock.js";
export type { IUpdateHost } from "../interfaces/i-update-host.js";
export type { IUpdateTarget } from "../interfaces/i-update-target.js";
export type { IUpdater } from "../interfaces/i-updater.js";
export type { ISenderFrame } from "../interfaces/i-sender-frame.js";
export type { ISessionHost } from "../interfaces/i-session-host.js";
export type { ISpellCheckHost } from "../interfaces/i-spell-check-host.js";
export type { IShellHost } from "../interfaces/i-shell-host.js";
export type { ISystemNotification } from "../interfaces/i-system-notification.js";
export type { IUtilityProcessHost } from "../interfaces/i-utility-process-host.js";
export type { IUtilityProcess } from "../interfaces/i-utility-process.js";
export type { IContextMenuParams } from "../interfaces/i-context-menu-params.js";
export type { IWindowContents } from "../interfaces/i-window-contents.js";
export type { IWindowStateStore } from "../interfaces/i-window-state-store.js";
export { MainProcessFailureKind } from "../enums/main-process-failure-kind.js";
export { PathCommandOutcome } from "../enums/path-command-outcome.js";
export { QuitChoice } from "../enums/quit-choice.js";
export { QuitOutcome } from "../enums/quit-outcome.js";
export { StartupStateKind } from "../enums/startup-state-kind.js";
export { UpdateStateKind } from "../enums/update-state-kind.js";
export { WindowErrorAdmission } from "../enums/window-error-admission.js";
export { DeviceIdentityException } from "../exceptions/device-identity.exception.js";
export { PathCommandException } from "../exceptions/path-command.exception.js";
export { ProgramException } from "../exceptions/program.exception.js";
export { UpdateException } from "../exceptions/update.exception.js";
export { UpdateHandoffException } from "../exceptions/update-handoff.exception.js";
export { UpdateStopException } from "../exceptions/update-stop.exception.js";
export { WindowStateException } from "../exceptions/window-state.exception.js";
export { WindowStateUnavailableException } from "../exceptions/window-state-unavailable.exception.js";
export { DesktopSettings } from "../models/desktop-settings.js";
export { DetachedStartReply } from "../models/detached-start-reply.js";
export { DetachedStartRequest } from "../models/detached-start-request.js";
export { FeedSource } from "../models/feed-source.js";
export { QuitQuestion } from "../models/quit-question.js";
export { StartedProgram } from "../models/started-program.js";
export { TaskbarIdentity } from "../models/taskbar-identity.js";
export { UpdateReadyRecord } from "../models/update-ready-record.js";
export { UpdateStatus } from "../models/update-status.js";
export { ScreenArea } from "../models/screen-area.js";
export { SenderInfo } from "../models/sender-info.js";
export { StartupState } from "../models/startup-state.js";
export { WindowAppearance } from "../models/window-appearance.js";
export { WindowState } from "../models/window-state.js";
export { ChildProgramHost } from "../services/child-program-host.js";
export { CloseCoordinator } from "../services/close-coordinator.js";
export { UpdateSaveCoordinator } from "../services/update-save-coordinator.js";
export { DesktopApplication } from "../services/desktop-application.js";
export { DesktopLog } from "../services/desktop-log.js";
export { DesktopRecord } from "../services/desktop-record.js";
export { DetachedStart } from "../services/detached-start.js";
export { DeviceFileStore } from "../services/device-file-store.js";
export { DeviceIdentity } from "../services/device-identity.js";
export { DeviceState } from "../services/device-state.js";
export { FeedProvider } from "../services/feed-provider.js";
export { FeedUpdater } from "../services/feed-updater.js";
export { LinkPolicy } from "../services/link-policy.js";
export { MainProcessRecovery } from "../services/main-process-recovery.js";
export { OpenWindow } from "../services/open-window.js";
export { PathCommand } from "../services/path-command.js";
export { PublisherCheck } from "../services/publisher-check.js";
export { QuitCoordinator } from "../services/quit-coordinator.js";
export { QuitFlow } from "../services/quit-flow.js";
export { UpdateController } from "../services/update-controller.js";
export { UpdateStop } from "../services/update-stop.js";
export { AppImageReplacement } from "../services/app-image-replacement.js";
export { AppImageRestart } from "../services/app-image-restart.js";
export { InstallerStart } from "../services/installer-start.js";
export { ShipItProcess } from "../services/ship-it-process.js";
export { UpdateWorkQuestion } from "../services/update-work-question.js";
export { RuntimeStartup } from "../services/runtime-startup.js";
export { RuntimeWindowStateStore } from "../services/runtime-window-state-store.js";
export { SenderPolicy } from "../services/sender-policy.js";
export { SpellChecker } from "../services/spell-checker.js";
export { SpellingDictionaries } from "../services/spelling-dictionaries.js";
export { SystemNotifier } from "../services/system-notifier.js";
export { TrayHostWatcher } from "../services/tray-host-watcher.js";
export { UpdateBarrierGate } from "../services/update-barrier-gate.js";
export { UpdateBarrierWatch } from "../services/update-barrier-watch.js";
export { UpdateCheckLock } from "../services/update-check-lock.js";
export { UtilityProcessStarter } from "../services/utility-process-starter.js";
export { WindowBoundsKeeper } from "../services/window-bounds-keeper.js";
export { WindowErrorLimit } from "../services/window-error-limit.js";
export { WindowRecovery } from "../services/window-recovery.js";
