/**
 * @license
 * Copyright (c) Noldova.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Theme } from "../models/theme";
import { Resources } from "../../resources";

export class DefaultTheme {
  public static readonly theme: Theme = new Theme(
    Resources.defaultThemeId,
    Resources.defaultThemeName,
    new Map([
      ["sideBar.background", "#F8F8F8"],
      ["editor.background", "#FFFFFF"],
      ["teamrun.raisedBackground", "#F8F8F8"],
      ["teamrun.codeBackground", "#F8F8F8"],
      ["teamrun.codeHeaderBackground", "#F2F2F2"],
      ["foreground", "#3B3B3B"],
      ["teamrun.mutedForeground", "#616161"],
      ["icon.foreground", "#3B3B3B"],
      ["surface.border", "#E5E5E5"],
      ["sideBarSectionHeader.border", "#E5E5E5"],
      ["focusBorder", "#005FB8"],
      ["textLink.foreground", "#005FB8"],
      ["list.hoverBackground", "#F2F2F2"],
      ["list.inactiveSelectionBackground", "#E4E6F1"],
      ["toolbar.hoverBackground", "#B8B8B850"],
      ["scrollbarSlider.background", "#64646466"],
      ["titleBar.activeBackground", "#F8F8F8"],
      ["titleBar.activeForeground", "#1E1E1E"],
      ["input.background", "#FFFFFF"],
      ["input.border", "#858585"],
      ["input.foreground", "#3B3B3B"],
      ["input.placeholderForeground", "#767676"],
      ["button.background", "#005FB8"],
      ["button.foreground", "#FFFFFF"],
      ["button.hoverBackground", "#0258A8"],
      ["button.secondaryBackground", "#E5E5E5"],
      ["button.secondaryForeground", "#3B3B3B"],
      ["button.secondaryHoverBackground", "#CCCCCC"],
      ["dropdown.background", "#FFFFFF"],
      ["dropdown.border", "#858585"],
      ["dropdown.listBackground", "#FFFFFF"],
      ["list.activeSelectionBackground", "#E8E8E8"],
      ["list.activeSelectionForeground", "#000000"],
      ["button.border", "#0000001A"],
      ["settings.headerForeground", "#1F1F1F"],
      ["editorHoverWidget.background", "#F8F8F8"],
      ["editorHoverWidget.border", "#3B3B3B33"],
      ["quickInput.background", "#F8F8F8"],
      ["menu.separatorBackground", "#3B3B3B33"],
      ["widget.shadow", "#00000029"],
      ["widget.border", "#E5E5E5"],
      ["dialog.background", "#F8F8F8"],
      ["menu.background", "#FFFFFF"],
      ["menu.foreground", "#3B3B3B"],
      ["menu.border", "#CECECE"],
      ["checkbox.background", "#F8F8F8"],
      ["checkbox.border", "#858585"],
      ["badge.background", "#CCCCCC"],
      ["badge.foreground", "#3B3B3B"],
      ["progressBar.background", "#005FB8"],
      ["notifications.background", "#FFFFFF"],
      ["notifications.border", "#E5E5E5"],
      ["errorForeground", "#A1260D"],
      ["teamrun.addedForeground", "#3F6212"]
    ]),
    new Map([
      ["sideBar.background", "#181818"],
      ["editor.background", "#1F1F1F"],
      ["teamrun.raisedBackground", "#2B2B2B"],
      ["teamrun.codeBackground", "#181818"],
      ["teamrun.codeHeaderBackground", "#2B2B2B"],
      ["foreground", "#CCCCCC"],
      ["teamrun.mutedForeground", "#9D9D9D"],
      ["icon.foreground", "#CCCCCC"],
      ["surface.border", "#252526"],
      ["sideBarSectionHeader.border", "#2B2B2B"],
      ["focusBorder", "#4DAAFC"],
      ["textLink.foreground", "#4DAAFC"],
      ["list.hoverBackground", "#2A2D2E"],
      ["list.inactiveSelectionBackground", "#37373D"],
      ["toolbar.hoverBackground", "#5A5D5E50"],
      ["scrollbarSlider.background", "#79797966"],
      ["titleBar.activeBackground", "#181818"],
      ["titleBar.activeForeground", "#CCCCCC"],
      ["input.background", "#313131"],
      ["input.border", "#858585"],
      ["input.foreground", "#CCCCCC"],
      ["input.placeholderForeground", "#989898"],
      ["button.background", "#0078D4"],
      ["button.foreground", "#FFFFFF"],
      ["button.hoverBackground", "#026EC1"],
      ["button.secondaryBackground", "#00000000"],
      ["button.secondaryForeground", "#CCCCCC"],
      ["button.secondaryHoverBackground", "#2B2B2B"],
      ["dropdown.background", "#313131"],
      ["dropdown.border", "#858585"],
      ["dropdown.listBackground", "#1F1F1F"],
      ["list.activeSelectionBackground", "#04395E"],
      ["list.activeSelectionForeground", "#FFFFFF"],
      ["button.border", "#FFFFFF1A"],
      ["settings.headerForeground", "#FFFFFF"],
      ["editorHoverWidget.background", "#202020"],
      ["editorHoverWidget.border", "#CCCCCC33"],
      ["quickInput.background", "#222222"],
      ["menu.separatorBackground", "#454545"],
      ["widget.shadow", "#0000005C"],
      ["widget.border", "#313131"],
      ["dialog.background", "#202020"],
      ["menu.background", "#1F1F1F"],
      ["menu.foreground", "#CCCCCC"],
      ["menu.border", "#454545"],
      ["checkbox.background", "#313131"],
      ["checkbox.border", "#858585"],
      ["badge.background", "#616161"],
      ["badge.foreground", "#F8F8F8"],
      ["progressBar.background", "#4DAAFC"],
      ["notifications.background", "#1F1F1F"],
      ["notifications.border", "#454545"],
      ["errorForeground", "#F48771"],
      ["teamrun.addedForeground", "#B5CEA8"]
    ]),
    new Map([
      ["radius-hover", "0.1875rem"],
      ["radius-small", "0.25rem"],
      ["radius-medium", "0.375rem"],
      ["radius-large", "0.5rem"],
      ["space-1", "0.25rem"],
      ["space-2", "0.5rem"],
      ["space-3", "0.75rem"],
      ["space-4", "1rem"],
      ["space-6", "1.5rem"],
      ["border-width", "1px"],
      ["shadow-large", "0 0 0.75rem rgb(0 0 0 / 14%)"],
      ["shadow-xlarge", "0 0 1.25rem rgb(0 0 0 / 15%)"],
      ["backdrop", "rgb(0 0 0 / 50%)"],
      ["panel-card-gap", "0.25rem"],
      ["tab-height", "2rem"],
      ["tab-pill", "1.5rem"],
      ["tab-inset", "0.125rem"],
      ["tab-label-inset", "0.5rem"],
      ["tab-action-allowance", "1.75rem"],
      ["tab-action-slot", "1.5rem"],
      ["tab-close", "1.25rem"],
      ["icon", "1rem"],
      ["icon-button", "1.375rem"],
      ["sash", "0.25rem"],
      ["sash-grip", "0.125rem"],
      ["sash-grip-spacing", "0.3125rem"],
      ["docking-guide", "2.5rem"],
      ["docking-guide-icon", "1.5rem"],
      ["docking-plate-gap", "0.125rem"],
      ["menu-padding", "0.25rem"],
      ["menu-label-padding", "0.5rem 0.75rem 0.25rem"],
      ["menu-item-height", "1.625rem"],
      ["menu-item-inset", "0.25rem"],
      ["menu-item-padding", "0.5rem"],
      ["menu-separator-spacing", "0.3125rem"],
      ["tooltip-width", "43.75rem"],
      ["tooltip-padding", "0.125rem 0.5rem"],
      ["window-row-height", "2.1875rem"],
      ["status-bar-height", "1.25rem"],
      ["status-bar-inset", "0.5rem"],
      ["status-bar-item-padding", "0.375rem"],
      ["status-bar-item-gap", "0.25rem"]
    ]),
    new Map([["tab", "pill"]]));
}
