/**
 * @license
 * Copyright (c) Noldova.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */

import * as api from "@noldova/teamrun-shell-runtime";
import { Assert, TestClass, TestMethod } from "@noldova/teamrun-foundation-testing";

@TestClass
export class RuntimeApiTests {
  @TestMethod
  public exportsTheCompleteCatalog(): void {
    const exportNames = [
      "AddonLoadException",
      "AppImageCopyCleanup",
      "AppImageSource",
      "AttachOptions",
      "BackupVerificationException",
      "BuildComparer",
      "BuildMismatchException",
      "BuildRelation",
      "CapabilityToken",
      "ChildProcessStarter",
      "ClientSettings",
      "CommandRegistry",
      "ConnectionException",
      "DataDirectory",
      "DataDirectoryInspection",
      "DataDirectoryInspector",
      "DataDirectoryLocator",
      "DataDirectoryOwnedException",
      "DataDirectoryState",
      "DatabaseBackup",
      "DeclarationsFormatException",
      "DiscoveryFormatException",
      "DiagnosticRedactor",
      "DiscoveryPublisher",
      "DiscoveryReader",
      "Endpoint",
      "EndpointKind",
      "EventChannel",
      "EventRegistry",
      "FolderProtectorFactory",
      "IdleMonitor",
      "LaunchException",
      "LaunchSettings",
      "LogFile",
      "LogText",
      "MethodFailureException",
      "MethodRegistry",
      "Migration",
      "MigratedDatabase",
      "MigrationException",
      "ModuleContext",
      "ModuleDatabase",
      "ModuleDatabaseException",
      "ModuleDeclaration",
      "ModuleDeclarationReader",
      "ModuleHost",
      "ModuleLoadException",
      "NoRuntimeException",
      "NotificationCenter",
      "NotificationHandle",
      "NotificationPolicy",
      "NotificationSettings",
      "OwnershipLock",
      "OwnedProcess",
      "OwnershipReleasedException",
      "PackageRuntimePartLoader",
      "PosixFolderProtector",
      "PreShellDataException",
      "PreShellDataFoundException",
      "ProcessClock",
      "ProcessExit",
      "ProcessLaunchCommand",
      "ProcessRequest",
      "ProcessSettings",
      "ProcessStartException",
      "ProcessSupervisor",
      "ProductFileException",
      "ProductInfo",
      "Refusal",
      "Registration",
      "RegistrationException",
      "RequestContext",
      "RuntimeBuild",
      "RuntimeClient",
      "RuntimeCommand",
      "RuntimeDiscovery",
      "RuntimeEntry",
      "RuntimeHandoverException",
      "RuntimeHost",
      "RuntimeLauncher",
      "RuntimeLog",
      "RuntimeOptions",
      "RunningProgram",
      "RuntimeServer",
      "ServerSettings",
      "ServiceAccessException",
      "ServiceRegistry",
      "SettingException",
      "SettingsService",
      "ShellDatabase",
      "ShellMigrations",
      "ShellSettings",
      "SystemCommand",
      "SystemCommandException",
      "UnknownSchemaException",
      "UpdateBarrier",
      "UpdateBarrierState",
      "UpdateBarrierStatus",
      "UpdateInProgressException",
      "ConnectedClient",
      "DeviceFolder",
      "Installation",
      "ProcessPresence",
      "WindowsFolderProtector",
      "WorkInProgressException",
      "WorkItem",
      "WorkTracker"
    ];

    Assert.areEqual(exportNames.sort().join(","), Object.keys(api).sort().join(","));
  }
}
